# Generated by Django 2.2.28 on 2022-08-22 21:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Группировка задач', max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, help_text='Описание группы', null=True, verbose_name='Описание группы')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Задача', max_length=70, verbose_name='Загодовок задачи')),
                ('description', models.TextField(blank=True, help_text='Описание задачи', null=True, verbose_name='Описание задачи')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 0, 16, 6, 330945), help_text='Запланированнвя дата', verbose_name='Запланированная дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('group', models.ForeignKey(blank=True, help_text='Группировка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_group', to='list.Group', verbose_name='Группа')),
            ],
        ),
    ]
