# Generated by Django 4.2.5 on 2023-10-04 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20220823_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.TextField(help_text='Название группы', max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 16, 39, 1, 547218), help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание задачи'),
        ),
    ]
