# Generated by Django 4.2.5 on 2023-10-07 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_group_title_alter_task_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 15, 27, 54, 910119), help_text='Дедлайн', verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 7, 15, 27, 54, 910119), help_text='Дата создания', verbose_name='Дата создания'),
        ),
    ]
