# Generated by Django 2.2.28 on 2022-08-20 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20220820_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 19, 29, 52, 847767), help_text='Запланированнвя дата', verbose_name='Запланированная дата'),
        ),
    ]
