# Generated by Django 4.2.5 on 2023-10-10 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_task_deadline_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 19, 27, 1, 212037), help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 10, 19, 27, 1, 212037), help_text='Дедлайн', null=True, verbose_name='Дедлайн'),
        ),
    ]
